In [1]:
#we may need some code in the ../python directory and/or matplotlib styles
import sys
sys.path.append('../python/')

#matplotlib for plotting
import matplotlib as mpl
from matplotlib import pyplot as plt
plt.style.use('mplstyles/stylelib/standard.mplstyle')

#other computational libraries
import numpy as np

In [2]:
npegs=27
nboxes=36
pn = np.zeros((npegs,))

pn[0]=36-9
pn[3]=9

pn=pn/36

print(pn)

[0.75 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]


In [3]:
def fairness(v):
    retval=0
    for i,p in enumerate(v):
        if (i>0) & (p>0):
            retval+=p*np.log(p)
    return -10*retval
            
            
            
print(fairness(pn))

3.4657359027997265


In [4]:
#looking for a data structure to represent pegs and grid
grid = np.zeros((6,6))

print(grid)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
grid[0,0] = 3
grid[0,1] = 3
grid[0,2] = 3

grid[1,0] = 3
grid[1,1] = 3
grid[1,2] = 3

grid[2,0] = 3
grid[2,1] = 3
grid[2,2] = 3

In [6]:
print(grid)

[[3. 3. 3. 0. 0. 0.]
 [3. 3. 3. 0. 0. 0.]
 [3. 3. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
#find out how many energy pegs total in the grid structure
print(np.sum(grid))

27.0


In [8]:
#print out every individual box value
for v in grid:
    for n in v:
      print(n)

3.0
3.0
3.0
0.0
0.0
0.0
3.0
3.0
3.0
0.0
0.0
0.0
3.0
3.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [11]:
#get total number of grid spaces
print(grid.size)

36
